# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
'''python
Import hashlib
Import hmac
Import binascii
Import random
Def generate_hash (password):
Salt = b"somesalt"# replace with
Actual salt value
H =hashlib.sha256(password + salt)
Return h.hexdigest()
Def check_hash(username,password):
Salt =b"somesalt"# replace with actual salt value
H = hashlib.sha256((username+password).encode())
If len(h.digest())==32 and h==
Generate_hash(password):
Return true
Else:
Return false
```
